name: App with Github Actions, ArgoCD

on:
  workflow_dispatch # 수동 실행 이벤트 정의
  # push # 즉시 반영

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Make application.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES }}" > ./application.properties
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Naming jar file
      run: mv ./build/libs/*.jar ./build/libs/app.jar

    - name: Check jar file
      run: ls ./build/libs

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./build/libs/*.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
    
    - uses: actions/checkout@v4
      with:
        repository: ${{ secrets.MY_ID }}/app-with-argocd-manifest
        ref: main
        token: ${{ secrets.TOKEN }}
    
    - name: Set up Image
      run: |
        sed -i "s%image: ${{ secrets.DOCKERHUB_USERNAME }}/app-with-argocd:[A-z0-9]*%image: ${{ secrets.DOCKERHUB_USERNAME }}/app-with-argocd:${{ github.sha }}%" ./manifest/argocd-app.yaml

    - name: Commit and push changes
      run: |
        git config --local user.email ""
        git config --local user.name ""
        git add .
        git commit -m "Update application image to latest"
        git push
